# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-04 08:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roasts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keys',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 4, 8, 14, 0, 953761)),
        ),
    ]
