# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-16 08:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roasts', '0003_auto_20161204_0849'),
        ('roasts', '0004_roast_user'),
    ]

    operations = [
    ]
