# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-21 03:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roasts', '0008_auto_20170119_2110'),
        ('roasts', '0008_auto_20170121_0044'),
    ]

    operations = [
    ]
