# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-21 05:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roasts', '0009_merge'),
        ('roasts', '0009_merge_20170121_0354'),
    ]

    operations = [
    ]
