# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-23 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roasts', '0010_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keys',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='roast',
            name='body',
            field=models.CharField(max_length=200),
        ),
    ]
