# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 19:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roasts', '0011_auto_20170223_0833'),
    ]

    operations = [
    	migrations.RenameModel('Keys', 'Key')
    ]
