# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 19:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roasts', '0012_auto_20170225_1903'),
    ]

    operations = [
    	migrations.RenameModel('Rate', 'Rating')
    ]
