# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roasts', '0013_auto_20170225_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='roast',
            name='total_rating',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
