# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 21:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('roasts', '0014_roast_total_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoastsOfTheDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('roast_1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='roast_1', to='roasts.Roast')),
                ('roast_2', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='roast_2', to='roasts.Roast')),
                ('roast_3', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='roast_3', to='roasts.Roast')),
                ('roast_4', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='roast_4', to='roasts.Roast')),
                ('roast_5', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='roast_5', to='roasts.Roast')),
            ],
        ),
    ]
