# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roasts', '0015_roastsoftheday'),
    ]

    operations = [
        migrations.AddField(
            model_name='roast',
            name='roast_of_the_day',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='roastsoftheday',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
