# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roasts', '0016_auto_20170421_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roast',
            name='roast_of_the_day',
            field=models.BooleanField(default=False),
        ),
    ]
