# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-02 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roasts', '0018_auto_20170421_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[(b'success', b'Success/Green'), (b'info', b'Info/Blue'), (b'warning', b'Warning/Yellow'), (b'danger', b'Danger/Red')], default=b'success', max_length=7)),
                ('message', models.CharField(max_length=130)),
                ('visible', models.BooleanField(default=False)),
            ],
        ),
    ]
